name: CML
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install CML and DVC
        run: |
          pip install cml dvc

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./src

      - name: Prepare data
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls
          python dataPreparing.py
        working-directory: ./src

      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls                
          python train.py 
        working-directory: ./src

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Start Create CML report"
          ls ./out

          echo "## Metrics" > report.md  
          cat ./out/metrics.txt >> report.md

          echo "## Confusion Matrix" >> report.md
          echo '![](./out/confusion_matrix.png "Confusion Matrix")' >> report.md

          cml comment create report.md


















# name: CML
# on: [push]
# permissions: write-all
# jobs:
#   train-and-report:
#     runs-on: ubuntu-latest

#     # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
#     steps:
#       - name: setup env
#       - uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '16'

#       - name: setup python         
#       - uses: actions/setup-python@v4

#       - name: setup CML 
#       - uses: iterative/setup-cml@v1
      
#       - name: setup DVC 
#       - uses: iterative/setup-dvc@v1


#       - name: install requirements
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
#           echo "requirement done"

#       - name: preparing data
#         env:
#           REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           ls
#           cd ./src
#           ls
#           python dataPreparing.py
#           echo "data preparing done"
      
#       - name: Train model
#         env:
#           REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           ls
#           cd ./src
#           ls                
#           python train.py 
#           echo "train done"
#       - name: Train model
#         env:
#           REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           # Create CML report
#           echo "Start Create CML report"
#           ls
#           cd ./out
#           ls 

#           echo "## Metrics" > report.md  
#           cat metrics.txt >> report.md

#           echo "## Confusion Matrix" >> report.md
#           echo '![](confusion_matrix.png "Confusion Matrix")' >> report.md

#           echo "CML report done"
#           cml comment create report.md